# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
